baseURL = "https://supple-waste.github.io/supple-waste/"
languageCode = "en-us"
title = "Supple Waste"
theme = "hermit"
publishDir = "docs"
googleAnalytics = "UA-131418336-1"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0800"

[menu]

  [[menu.main]]
    name = "Poems"
    url = "/poems/"
    weight = 10

